### ISSUE TITLE
Sign the csrftoken cookie value

### ISSUE THREAD

**Issue by simonw** [simonw/asgi-csrf#2]
https://owasp.org/www-project-cheat-sheets/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet#double-submit-cookie has some warnings:

> While it’s true that hellokitty.marketing.example.com cannot read cookies or access the DOM from secure.example.com because of the same origin policy, hellokitty.marketing.example.com can write cookies to the parent domain (example.com), and these cookies are then consumed by secure.example.com (secure.example.com has no good way to distinguish which site set the cookie).

And:

> b) If an attacker is in the middle, they can usually force a request to the same domain over HTTP. If an application is hosted at https://secure.example.com, even if the cookies are set with the secure flag, a man in the middle can force connections to http://secure.example.com and set (overwrite) any arbitrary cookies (even though the secure flag prevents the attacker from reading those cookies). Even if the HSTS header is set on the server and the browser visiting the site supports HSTS (this would prevent a man in the middle from forcing plaintext HTTP requests) unless the HSTS header is set in a way that includes all subdomains, a man in the middle can simply force a request to a separate subdomain and overwrite cookies similar to 1. In other words, as long as http://hellokitty.marketing.example.com doesn’t force https, then an attacker can overwrite cookies on any example.com subdomain.

Encouraging users to serve over HTTPS can help here, but to ensure no-one sets a known cookie value using an HTTP interception hack I should sign the cookie value with a secret.

I can use https://itsdangerous.palletsprojects.com/ for this.

**Comment by JokerQyou** [comment]
Excerpted from the first link in your comment:

> When a user visits (even before authenticating to prevent login CSRF), the site should generate a (cryptographically strong) pseudorandom value and set it as a cookie on the user’s machine separate from the session identifier.

But I think since `starlette`'s `SessionMiddleware` already signs the session cookie, maybe it is secure enough to put the CSRF token into session data?

Of course it's not practical to do so because this library should not be bound to `starlette`.

**Comment by simonw** [comment]
Yeah if I could rely on the presence of sessions I'd use those, but I'm trying to make sure this works independently.

**Comment by simonw** [comment]
The biggest challenge with this is where should the secret come from?

I'm going to have the middleware look for a secret in the following places:

1. An argument passed to the class
2. An environment variable - `ASGI_CSRF_SECRET`
3. If neither of those, it will generate a random secret

The random secret will be regenerated on each startup so if a user is unlucky they may have a stale signed value when they submit a form (if the server has restarted). For that reason I will recommend users set a secret using one of the other two mechanisms.

**Comment by JokerQyou** [comment]
Beside mentioning in documentation, emit a warning message right before generating a random secret might be a good idea as well.

**Comment by simonw** [comment]
I'm going to use itsdangerous which delightfully has zero additional dependencies of its own: https://pypi.org/project/itsdangerous

**Comment by simonw** [comment]
Re-opening because I need to add documentation about the signing secret.
